# Neural Network

## Imports

In [51]:
import numpy as np
from keras.datasets import mnist
from keras.utils import np_utils

## Activatie functies, mean squared error en hun afgeleides

In [52]:
def sig(x):
     return 1/(1 + np.exp(-x))

def relu(x):
    return max(0.0, x)

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

def der_relu(x):
    return relu(x)

def der_sig(x):
    return sig(x) * (1.0 - sig(x))

def mse(y_true, y_pred):
    return np.mean(np.power(y_true-y_pred, 2));

def der_mse(y_true, y_pred):
    return 2*(y_pred-y_true)/y_true.size;

## Layer

In [53]:
class Layer():
    # het initialiseren van de laag
    def __init__(self, input_data, output_data, activation, der_activation):
        self.input = None
        self.output = None
        # er wordt een random getal tussen 0 en 1 gemaakt bij de weights en biases
        # voor de weights wordt er een array gemaakt met het 'input_data' aantal aan data 
        # en 'outpout'het aantal getallen elk rij heeft en daarna wordt een half ervan afgehaald
        self.weights = np.random.rand(input_data, output_data) - 0.5
        # voor de bias wordt er een rij gemaakt met 5 random values en van elke value wordt daarna een halve afgehaald
        self.bias = np.random.rand(1, output_data) - 0.5
        self.activation = activation
        self.der_activation = der_activation
    
    # berekend het output van een laag
    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = self.activation(np.dot(self.input, self.weights) + self.bias)
        return self.output
    
    # berekend de backprogation en verbeterd hierbij ook de weights en biases aan de hand van de learning rate
    def backward_propagation(self, output_error, learning_rate):
        input_error = self.der_activation(self.output) * output_error
        input_error = np.dot(input_error, self.weights.T)
        
        weights_error = np.dot(self.input.T, output_error)
        
        self.weights -= learning_rate * weights_error
        self.bias -= learning_rate * output_error
        
        return input_error

## Network samenstellen

In [67]:
class Network:
    #netwerk initialiseren
    def __init__(self):
        self.layers = []
        self.cost = None
        self.der_cost = None 
    
    # een functie voor het toevoegen van de laag
    def add(self, layer):
        self.layers.append(layer)
    
    # een functie waarbij de kostfunctie en de afgeleide ervan wordt meegegeven
    def use(self, cost, der_cost):
        self.cost = cost
        self.der_cost = der_cost
    
    # deze predict functie wordt gebtuikt voor het uitvoeren van de nn
    def predict(self, input_data):
        # om de dimensie/lengte van de de input data
        samples = len(input_data)
        # leeg array die alle resultaten bewaart
        result = []
        
        # er wordt gelooped aan de hand van elke lengte van de data
        for i in range(samples):
            # de output wordt hier al geinitialiseerd en wordt het inputdata
            output = input_data[i]
            # voor elke laag in het network wordt de input gestuurd naar de forward propegation van de laag en wordt de return 
            # toegevoegd aan de array
            for layer in self.layers:
                output = layer.forward_propagation(output)
            result.append(output)

        return result
    
    #de fit functie is voor het trainen van het netwerk
    def fit(self, x_train, y_train, epochs, learning_rate):
        samples = len(x_train)
        
        #een epoch is wanneer de data voor het trainen een keer helemaal door het netwerk is gegaan
        for i in range(epochs):
            err = 0
            
            #net zoals bij de predict methode wordt aan de hand van de lengte elke data naar de feedforward gestuurd
            for j in range(samples):
                output = x_train[j]
                for layer in self.layers:
                    output = layer.forward_propagation(output)
                
                # aan de hand van de output wordt de resultaat met het gewilde antwoord vergeleken
                err += self.cost(y_train[j], output)
                
                # aan de hand van de afgeleide van de mse weten de richting waarin we de parameters aanpassen
                error = self.der_cost(y_train[j], output)
                for layer in reversed(self.layers):
                    error = layer.backward_propagation(error, learning_rate)
            
            # het gemiddelde van alle trainingsdatta
            err /= samples
            print('epoch %d/%d   error=%f' % (i+1, epochs, err))

## Een kleine test

In [68]:
x_train = np.array([[[0,0]], [[0,1]], [[1,0]], [[1,1]]])
y_train = np.array([[[0]], [[1]], [[1]], [[0]]])

In [69]:
net = Network()
net.add(Layer(2, 3, sig, der_sig))
net.add(Layer(3, 1, relu, der_relu))

In [70]:
net.use(mse, der_mse)
net.fit(x_train, y_train, epochs=10, learning_rate=0.1)

epoch 1/10   error=0.515989
epoch 2/10   error=0.376097
epoch 3/10   error=0.346439
epoch 4/10   error=0.346506
epoch 5/10   error=0.346270
epoch 6/10   error=0.345771
epoch 7/10   error=0.345229
epoch 8/10   error=0.344692
epoch 9/10   error=0.344172
epoch 10/10   error=0.343668


## Testen met een grotere datasets

In [71]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [72]:
x_train = x_train.reshape(x_train.shape[0], 1, 28*28)
x_train = x_train.astype('float32')
x_train /= 255

In [73]:
y_train = np_utils.to_categorical(y_train)

In [74]:
x_test = x_test.reshape(x_test.shape[0], 1, 28*28)
x_test = x_test.astype('float32')
x_test /= 255
y_test = np_utils.to_categorical(y_test)

In [75]:
net = Network()
net.add(Layer(28*28, 100, sig, der_sig))
net.add(Layer(100, 50, sig, der_sig)) 
net.add(Layer(50, 10, sig, der_sig))

In [76]:
net.use(mse, der_mse)
net.fit(x_train[0:1000], y_train[0:1000], epochs=50, learning_rate=0.1)

epoch 1/50   error=0.079482
epoch 2/50   error=0.050860
epoch 3/50   error=0.038651
epoch 4/50   error=0.031427
epoch 5/50   error=0.026657
epoch 6/50   error=0.023501
epoch 7/50   error=0.021347
epoch 8/50   error=0.019782
epoch 9/50   error=0.018550
epoch 10/50   error=0.017577
epoch 11/50   error=0.016845
epoch 12/50   error=0.016290
epoch 13/50   error=0.015811
epoch 14/50   error=0.015319
epoch 15/50   error=0.014772
epoch 16/50   error=0.014176
epoch 17/50   error=0.013563
epoch 18/50   error=0.012962
epoch 19/50   error=0.012360
epoch 20/50   error=0.011751
epoch 21/50   error=0.011185
epoch 22/50   error=0.010681
epoch 23/50   error=0.010218
epoch 24/50   error=0.009829
epoch 25/50   error=0.009550
epoch 26/50   error=0.009418
epoch 27/50   error=0.009433
epoch 28/50   error=0.009440
epoch 29/50   error=0.009385
epoch 30/50   error=0.009271
epoch 31/50   error=0.009119
epoch 32/50   error=0.009028
epoch 33/50   error=0.008966
epoch 34/50   error=0.008891
epoch 35/50   error=0.0

In [77]:
for i in range(len(x_test)):
    out = net.predict(x_test[i])
    print("predicted values - true values : " )
    print(out)
    print(" - ")
    print(y_test[i])
    print("\n")

predicted values - true values : 
[array([[3.88538404e-03, 3.18313761e-06, 1.62427264e-02, 8.00098905e-04,
        2.27582388e-05, 2.49461834e-05, 4.61611674e-06, 9.98259419e-01,
        1.47839016e-05, 4.26201618e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[4.67080041e-02, 1.59792454e-05, 9.54141495e-02, 3.63364807e-01,
        1.74583250e-06, 8.42976352e-03, 6.81628988e-02, 1.74432907e-05,
        1.90741683e-06, 1.04663503e-03]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.82859319e-07, 9.68634748e-01, 1.30730111e-02, 1.01976384e-02,
        3.18841120e-05, 2.18864516e-06, 2.19730660e-04, 6.41784163e-02,
        1.04937136e-04, 9.73155433e-05]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[8.94075695e-01, 1.13253282e-05, 1.25614831e-03, 3.40802350e-05,
        1.96503669e-05, 3.71743807e-04, 1.65610800e-02, 2.60482162e-01,
        4.36880051e-08, 4.00183370e-04]])

predicted values - true values : 
[array([[1.84641119e-04, 1.70792688e-04, 1.58804909e-04, 6.52574595e-06,
        9.18039574e-01, 1.89880577e-06, 1.33382561e-03, 6.32419892e-02,
        3.36834850e-07, 9.14539513e-03]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.51565997e-03, 2.75593248e-05, 6.97370937e-04, 4.96741939e-05,
        4.76780268e-05, 5.30338889e-03, 8.98835986e-01, 1.69887608e-06,
        1.27941109e-06, 2.10116003e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[3.97890985e-04, 1.45192326e-04, 1.64568686e-04, 9.94258334e-01,
        6.31074910e-05, 1.17420199e-01, 1.99205470e-04, 1.31869622e-04,
        8.06960385e-06, 6.63794606e-06]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[5.47447956e-03, 1.29357961e-04, 1.63374825e-09, 5.80861631e-05,
        5.62790634e-01, 7.30521432e-01, 1.21543571e-05, 5.45240327e-04,
        2.06019025e-08, 4.26505980e-05]])

predicted values - true values : 
[array([[2.33243393e-05, 2.63525221e-04, 5.96862186e-05, 1.73831097e-03,
        9.74024434e-01, 7.04979508e-06, 5.50765953e-01, 7.10680838e-06,
        6.18654820e-09, 2.05933199e-03]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.00621159e-07, 5.28881369e-04, 1.29253635e-03, 1.35366104e-06,
        9.80846614e-03, 6.00818764e-03, 9.96621683e-01, 1.33262251e-05,
        2.83378196e-05, 1.01606437e-05]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[4.03792216e-02, 1.24289170e-05, 8.20044770e-01, 6.21178052e-04,
        3.71619821e-04, 1.06173083e-03, 1.53471700e-06, 1.77253260e-01,
        2.72868585e-05, 3.60954640e-05]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.96685072e-08, 5.20205236e-01, 9.23699233e-01, 1.33883692e-02,
        8.41687686e-05, 8.73065637e-07, 7.32182889e-02, 4.05740383e-04,
        6.26948227e-05, 1.20706956e-03]])

predicted values - true values : 
[array([[1.88207092e-08, 6.02608944e-02, 5.51325394e-06, 9.51114045e-01,
        3.76487296e-04, 4.99722265e-03, 2.27314203e-05, 1.54386256e-03,
        3.43693207e-04, 3.00487904e-04]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.12776928e-07, 5.48069012e-01, 5.74880992e-01, 6.72104098e-04,
        3.23322667e-06, 2.78800891e-03, 8.23900640e-03, 7.82713141e-05,
        2.52060523e-02, 4.23375554e-06]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[5.06973500e-08, 2.26694180e-03, 3.13094190e-09, 3.91919572e-01,
        2.46988040e-03, 2.69889700e-03, 5.51392205e-06, 1.36006039e-02,
        4.76012746e-06, 7.03854382e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[1.35767083e-05, 2.53998175e-04, 6.59841824e-03, 8.06177303e-06,
        1.09519439e-04, 8.34635783e-04, 6.37301040e-05, 9.92574318e-01,
        5.13375571e-04, 5.56814853e-05]])

predicted values - true values : 
[array([[1.86784489e-07, 9.92231891e-01, 1.42459153e-04, 3.79902777e-03,
        1.98348046e-06, 2.45208563e-05, 8.37819469e-04, 1.52119797e-02,
        2.63514027e-03, 2.12686812e-04]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[5.58973215e-05, 1.45929194e-05, 7.38852768e-07, 4.41657638e-03,
        9.94270549e-01, 4.65271105e-04, 4.76639584e-04, 7.75151948e-05,
        4.35901533e-05, 1.64085640e-02]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.54503127e-06, 1.47585882e-05, 1.18408734e-06, 1.06892895e-01,
        9.82451863e-01, 7.90780757e-04, 4.55562317e-04, 7.74889135e-05,
        3.86453836e-05, 2.66481940e-02]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.64505826e-05, 9.64847292e-04, 1.84516355e-08, 9.82252956e-01,
        9.50640178e-05, 2.46293761e-01, 1.33952243e-05, 4.70255183e-05,
        6.51482810e-07, 9.43269913e-02]])

predicted values - true values : 
[array([[1.19604889e-04, 8.96804350e-05, 1.22474167e-02, 6.07030912e-03,
        1.70452889e-04, 3.03801643e-02, 2.17789413e-06, 3.14081033e-05,
        1.51676788e-01, 6.65002977e-03]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.29857743e-07, 2.93449924e-05, 1.42457079e-01, 1.78059666e-03,
        9.37336822e-01, 2.58070848e-05, 1.36139300e-03, 5.92479678e-05,
        3.93282334e-04, 4.61253877e-03]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.96738816e-01, 1.75909185e-05, 1.08726104e-03, 3.72727434e-03,
        1.85873213e-06, 1.98238053e-01, 7.29503889e-06, 3.81900273e-04,
        3.23784172e-07, 7.07819274e-04]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[6.90079315e-07, 1.55232065e-02, 5.48505047e-03, 2.61217335e-07,
        3.29416041e-03, 8.77416383e-06, 9.44274484e-01, 4.47021379e-05,
        6.50472494e-04, 8.01621831e-02]])

predicted values - true values : 
[array([[6.95260695e-09, 3.63732773e-03, 5.73504226e-07, 6.53763983e-02,
        2.36595730e-03, 8.24570950e-04, 2.44009991e-06, 5.72017641e-03,
        3.65601508e-03, 8.44391127e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[4.19211988e-01, 1.62159716e-03, 1.08940968e-04, 1.84016048e-10,
        4.33061247e-06, 3.39886381e-02, 1.84886018e-01, 5.25979078e-03,
        2.45298621e-05, 5.40150229e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[5.55072789e-08, 2.15641351e-03, 4.14706833e-07, 8.56359783e-05,
        2.56833794e-01, 6.72039537e-04, 3.25451456e-05, 5.26194358e-03,
        3.55229842e-01, 2.35558555e-01]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.25505565e-03, 1.09172069e-03, 9.99480123e-01, 5.83012165e-04,
        8.80675527e-06, 2.28082463e-03, 1.12969664e-04, 1.73820627e-04,
        3.25351926e-04, 2.60566774e-05]])

predicted values - true values : 
[array([[2.75928599e-05, 5.41616056e-04, 1.11502368e-06, 2.41012673e-02,
        2.65916160e-01, 2.03823040e-01, 4.04822858e-03, 9.34641317e-06,
        5.63471146e-08, 3.54066961e-07]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.08786101e-05, 1.40676124e-02, 6.45801227e-05, 6.26834569e-08,
        7.32015409e-02, 2.72804393e-06, 9.45076909e-01, 4.91333661e-03,
        2.95487135e-05, 3.96294500e-03]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[7.95260469e-07, 9.82414544e-01, 3.85553846e-06, 8.52075855e-04,
        3.97904368e-06, 1.31601865e-05, 2.91041223e-03, 2.71814497e-01,
        5.60887344e-04, 1.96440188e-04]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.23325482e-09, 4.63209749e-02, 4.07781870e-07, 5.87715102e-01,
        6.93085975e-03, 5.71572633e-04, 1.94795048e-05, 2.77883076e-03,
        5.50125909e-04, 1.74485302e-01]])

predicted values - true values : 
[array([[2.36794745e-05, 7.83262884e-04, 2.11979513e-02, 2.70189056e-05,
        5.37806336e-04, 7.10569139e-06, 2.29198298e-05, 2.76166620e-02,
        9.90809812e-02, 7.62188001e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[5.64823439e-07, 1.14833316e-03, 2.85430983e-03, 8.37581630e-06,
        5.00104688e-05, 2.03125052e-02, 6.42732547e-04, 4.46423816e-05,
        9.57342260e-01, 8.18138867e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[4.97040288e-04, 1.65196579e-04, 9.99574269e-01, 3.54986625e-05,
        5.35184742e-05, 5.17452045e-03, 1.61684333e-01, 3.85691381e-06,
        1.10190526e-05, 1.56703988e-05]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.13988668e-02, 9.17038431e-06, 3.98276800e-05, 2.72424664e-05,
        8.55536551e-01, 3.45018169e-04, 6.31968988e-06, 4.01241360e-03,
        1.09378409e-06, 1.61294684e-02]])

predicted values - true values : 
[array([[1.33919209e-05, 2.32530818e-04, 4.59480090e-09, 1.79143508e-01,
        3.30669508e-05, 1.39423368e-02, 1.26866403e-05, 9.22427734e-01,
        5.14154875e-07, 3.55424783e-03]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.92229399e-09, 3.74842694e-01, 6.11183920e-05, 1.05397162e-02,
        2.14879665e-04, 3.69637803e-07, 6.52851158e-04, 4.48365105e-01,
        3.37992404e-04, 2.91172816e-01]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.92826519e-08, 9.83812529e-01, 2.64125512e-03, 8.93362191e-03,
        1.17467327e-04, 1.46664611e-06, 5.95760507e-04, 1.09019451e-02,
        7.20141617e-05, 3.53543033e-04]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.00746620e-04, 3.05616287e-04, 4.80900695e-04, 3.15138266e-07,
        4.55863030e-03, 9.49602139e-04, 9.93911901e-01, 2.74087570e-06,
        3.91873433e-06, 1.51823535e-03]])

predicted values - true values : 
[array([[2.26677885e-07, 1.48633488e-04, 3.06755930e-05, 1.18458235e-02,
        8.86180968e-01, 1.31498291e-06, 4.99626951e-03, 4.54761856e-03,
        3.37321691e-06, 4.31696419e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[8.71658315e-05, 1.28603199e-03, 2.60551669e-04, 9.91539498e-01,
        2.56389332e-04, 6.13023656e-02, 4.21632287e-04, 2.64471172e-05,
        1.35818533e-05, 2.40524016e-06]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[5.05933133e-04, 5.76473705e-06, 6.84829346e-08, 5.25611625e-04,
        4.76795999e-03, 4.49096292e-04, 7.29492688e-07, 9.89681913e-01,
        1.89275747e-06, 4.25508559e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[3.25195727e-09, 7.57902065e-01, 1.64607531e-05, 4.89087851e-01,
        1.96095089e-05, 2.80928063e-04, 4.08309119e-05, 9.29742486e-03,
        3.55291861e-04, 4.83281448e-03]])

predicted values - true values : 
[array([[1.63364647e-04, 1.05475671e-04, 1.61758858e-09, 1.98169324e-05,
        9.60906135e-01, 9.66379033e-03, 1.30384483e-04, 1.07240450e-03,
        2.92962199e-06, 1.58137981e-02]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.43043433e-06, 1.78798954e-04, 3.29245344e-04, 9.98575068e-01,
        8.08744245e-04, 5.54236496e-04, 2.89376597e-07, 4.22240236e-02,
        6.12244102e-04, 3.90175221e-03]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.61203768e-04, 6.07165553e-06, 7.80871907e-03, 4.51447242e-01,
        6.58516958e-05, 3.73729545e-04, 4.73401232e-06, 9.93387360e-01,
        2.69894892e-05, 2.12013116e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[2.07694068e-07, 2.29329532e-04, 1.90786313e-05, 1.73257681e-03,
        2.17354703e-04, 6.26271149e-05, 1.90938674e-06, 3.97895415e-02,
        3.16126388e-03, 9.98219772e-01]])

predicted values - true values : 
[array([[2.86624431e-02, 4.71400729e-06, 2.70070489e-04, 4.05618485e-04,
        4.23567172e-05, 3.21098291e-01, 1.42377338e-07, 5.53406070e-01,
        1.57645526e-03, 1.61712028e-05]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.02334336e-05, 1.60704958e-02, 9.66961055e-05, 3.73325526e-07,
        1.60003082e-04, 2.51393380e-05, 2.07136435e-02, 4.60338768e-03,
        1.43041793e-03, 2.11470789e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[1.91609485e-07, 1.16212124e-04, 1.47571015e-03, 5.41315485e-01,
        2.92394392e-04, 2.32455803e-04, 2.42690558e-06, 9.36375711e-05,
        6.19414266e-04, 9.96876610e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[7.71536856e-05, 1.53310459e-04, 2.44907866e-01, 5.49475233e-05,
        6.19391775e-03, 2.15798407e-04, 1.42996167e-05, 1.87388839e-05,
        3.28041878e-02, 3.18252834e-01]])

predicted values - true values : 
[array([[2.05736836e-09, 8.78766752e-01, 2.85519133e-05, 1.27303276e-01,
        1.48920734e-04, 1.89266214e-05, 1.96190371e-03, 8.08421898e-03,
        1.61529199e-05, 2.45464241e-03]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[7.69640187e-06, 1.00981566e-04, 7.41987275e-05, 2.44072211e-05,
        9.17026309e-06, 5.49492262e-04, 1.77479691e-06, 9.99596078e-01,
        1.33184210e-04, 2.14238140e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[4.63348488e-07, 1.10682574e-04, 3.18569303e-04, 8.91327490e-01,
        3.23879056e-04, 1.23797008e-05, 7.41707327e-07, 2.48336842e-01,
        1.02889015e-02, 9.30054366e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[2.68212628e-02, 9.14308082e-06, 2.93643982e-04, 1.33965779e-08,
        2.43460415e-01, 1.63348405e-01, 4.30206566e-05, 7.72263854e-05,
        1.13497555e-02, 2.82277785e-03]])

predicted values - true values : 
[array([[9.83932602e-05, 3.37377907e-04, 7.61949177e-04, 8.91399681e-07,
        1.55446554e-03, 3.26721332e-03, 9.96024665e-01, 6.10404119e-07,
        1.65115411e-05, 1.30767760e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[2.45263944e-07, 7.86567558e-03, 4.14408717e-01, 3.03761398e-05,
        1.12665247e-05, 6.00925508e-05, 3.92597082e-02, 6.98375281e-01,
        3.72792435e-05, 6.15185717e-05]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.00403865e-04, 1.68820405e-04, 4.66359096e-07, 9.86430780e-01,
        3.33242529e-04, 8.93559043e-03, 2.02971594e-06, 2.75358432e-02,
        4.09422779e-07, 5.18027493e-04]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.61211221e-07, 9.86892239e-01, 6.51091510e-05, 7.73632670e-04,
        5.91315340e-06, 9.65463878e-06, 1.16739119e-02, 1.06490194e-01,
        4.12398521e-04, 5.99267547e-05]])

predicted values - true values : 
[array([[9.91198472e-01, 2.68531834e-05, 1.88397853e-02, 2.93131868e-04,
        8.45751370e-07, 2.49196453e-02, 3.48123663e-05, 1.34944480e-03,
        2.96937682e-07, 6.37938069e-04]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.01103694e-05, 3.16759430e-05, 2.37849032e-05, 3.09761658e-03,
        7.38818484e-06, 2.21498771e-03, 1.58701971e-07, 9.99722233e-01,
        2.42589624e-05, 4.37427134e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[2.82188727e-03, 1.18656354e-05, 6.51752711e-07, 2.28318841e-04,
        9.65189010e-01, 6.51799252e-04, 1.00114497e-05, 6.60944028e-03,
        1.03926685e-06, 1.14548776e-02]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.61203942e-06, 1.12459994e-02, 9.83643439e-01, 4.41594995e-02,
        1.89384011e-05, 1.71331391e-04, 3.89798881e-04, 2.05049891e-03,
        1.22377613e-02, 4.42776980e-05]])

predicted values - true values : 
[array([[7.14578120e-02, 6.56550744e-05, 1.45876060e-01, 1.59619511e-06,
        5.16841745e-03, 1.80544242e-05, 4.72275173e-05, 2.83621480e-03,
        4.70968801e-06, 2.14109347e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[6.61083800e-07, 1.10749966e-03, 2.75467079e-03, 9.31415649e-06,
        9.35613765e-05, 1.33727791e-02, 8.70438418e-05, 3.65109758e-04,
        9.68359807e-01, 7.86661295e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[3.55231256e-05, 1.92028192e-04, 2.80539818e-02, 3.84300405e-05,
        1.03463539e-03, 8.64875629e-07, 2.96179918e-05, 8.79101797e-01,
        1.20543381e-04, 6.35819393e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[7.64280118e-06, 1.07268138e-02, 4.82484290e-03, 2.11623212e-05,
        3.39849029e-05, 7.91831618e-02, 2.53291997e-05, 1.23486342e-04,
        9.77435622e-01, 8.92421010e-04]])

predicted values - true values : 
[array([[8.31937869e-08, 9.63834500e-01, 1.44506234e-03, 4.88339725e-03,
        2.60996379e-04, 1.17220026e-06, 1.97965698e-04, 2.96190869e-02,
        7.97971683e-05, 5.39189058e-04]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.87704287e-05, 6.07749395e-04, 4.88378684e-02, 7.91488638e-06,
        5.43118444e-01, 5.58451437e-06, 5.39009338e-01, 5.61144198e-06,
        1.19054203e-07, 4.33815515e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[2.80044565e-03, 2.74411783e-05, 1.00535369e-01, 2.93067422e-03,
        2.15956969e-03, 7.91786534e-05, 1.09486930e-04, 3.12005334e-04,
        6.55241993e-06, 3.19142958e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[3.94934218e-06, 5.13308641e-03, 2.54664378e-03, 5.00342119e-06,
        5.31435136e-04, 3.03363777e-04, 1.98260370e-05, 5.68563489e-01,
        6.46779478e-01, 1.88570282e-03]])

predicted values - true values : 
[array([[3.45272004e-05, 4.33248896e-03, 1.17202710e-05, 4.59227627e-02,
        2.38858358e-07, 3.66844690e-02, 5.12658169e-03, 1.90735614e-02,
        1.74187906e-06, 2.42728156e-05]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.88750713e-01, 2.48176741e-06, 5.65084146e-04, 2.51610144e-04,
        4.48726109e-05, 1.11822023e-02, 2.75344819e-05, 1.74566558e-02,
        2.40531868e-07, 3.41486665e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.88766260e-06, 4.22164160e-03, 4.18597515e-03, 2.14234715e-05,
        3.95341732e-04, 3.07383417e-03, 4.36619543e-06, 1.25292466e-01,
        8.65252113e-01, 6.40898127e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[5.18411217e-08, 3.49534577e-02, 1.58642939e-08, 1.32891583e-04,
        2.45180836e-01, 2.97171907e-05, 1.16906215e-04, 1.55276963e-01,
        1.02682244e-03, 9.52002565e-02]])

predicted values - true values : 
[array([[4.99169770e-04, 1.21465121e-03, 1.01773507e-06, 4.55592910e-02,
        2.45723306e-04, 8.70673355e-01, 7.18855190e-04, 2.49806684e-05,
        4.39248831e-06, 2.07117110e-07]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.59949302e-05, 3.27031254e-02, 8.14681801e-05, 1.68026308e-06,
        9.60296198e-05, 4.72173109e-02, 7.48805634e-05, 3.28386812e-04,
        9.97190030e-01, 1.73193875e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[8.09359552e-08, 1.48522570e-04, 1.98443515e-04, 1.88095669e-02,
        2.03432807e-02, 6.58582857e-06, 1.23593842e-06, 2.77794831e-02,
        3.26597309e-03, 9.88102684e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[1.64844585e-07, 9.99235566e-01, 2.42841858e-08, 3.63150100e-06,
        2.11235309e-03, 3.97692986e-03, 1.44040535e-02, 1.06132541e-05,
        1.89013101e-03, 9.03132710e-05]])

predicted values - true values : 
[array([[1.82392173e-03, 1.69993328e-05, 1.14637054e-03, 2.67895534e-06,
        3.98325614e-01, 6.29147969e-05, 8.38860069e-01, 2.79918714e-04,
        1.49391306e-09, 3.64939277e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[4.93771921e-05, 1.80558426e-05, 1.40701682e-05, 5.92034394e-04,
        6.26157289e-06, 2.43712479e-03, 1.14730284e-07, 9.99765383e-01,
        2.70825077e-05, 1.71126399e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[6.35315574e-06, 1.07409451e-02, 8.16199241e-07, 4.28777606e-08,
        1.67382893e-02, 9.54311063e-02, 8.55761992e-03, 7.84744603e-05,
        8.02149874e-01, 2.42211854e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[4.09652826e-05, 1.61315091e-05, 3.67417770e-07, 2.62351080e-04,
        3.29841110e-04, 7.81606370e-03, 3.53372629e-05, 8.91832800e-05,
        3.86521260e-04, 9.96326353e-01]])

predicted values - true values : 
[array([[1.74616241e-04, 2.28139678e-04, 1.42064394e-05, 1.70505232e-06,
        8.67123423e-01, 1.57061990e-05, 2.13969895e-04, 4.14044368e-01,
        1.52004423e-06, 5.01873290e-03]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[8.23538420e-04, 2.62624646e-03, 9.94920201e-01, 5.63450667e-03,
        1.45606487e-04, 5.32576549e-04, 5.20516814e-06, 3.93858213e-05,
        2.64663138e-03, 3.83404627e-04]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.94877102e-01, 5.60807263e-06, 8.49410779e-04, 1.55675001e-04,
        3.04463534e-06, 5.27646024e-03, 2.61139572e-04, 2.82447223e-02,
        5.64244136e-07, 6.75481213e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.06963137e-06, 6.18905357e-05, 4.23776260e-04, 1.87035071e-05,
        6.29141623e-05, 5.52535117e-05, 8.07167591e-06, 9.65244220e-01,
        1.27748886e-04, 7.97149690e-01]])

predicted values - true values : 
[array([[3.10182450e-07, 9.71800928e-01, 3.40683951e-03, 8.76527364e-03,
        1.96396704e-06, 9.47387806e-06, 2.39829783e-03, 1.12781043e-01,
        2.06499673e-04, 2.04911204e-05]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.36393087e-03, 9.71611409e-05, 9.60882374e-01, 7.64086097e-04,
        4.30756939e-03, 7.17988570e-04, 4.59975917e-06, 4.57949539e-05,
        6.06445143e-04, 9.24788490e-04]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.27050462e-06, 3.14056914e-03, 9.01715870e-04, 9.89874549e-01,
        1.38152521e-03, 1.98475216e-03, 1.55836730e-07, 1.50475399e-03,
        2.81916777e-03, 1.77352653e-04]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.64606587e-04, 1.82724910e-04, 3.70124753e-05, 1.66318047e-03,
        9.57156243e-01, 2.03571039e-05, 5.04904088e-02, 1.99325502e-05,
        8.78942704e-09, 1.46268151e-03]])

predicted values - true values : 
[array([[8.78980891e-01, 4.62284994e-06, 4.59603323e-04, 2.94339433e-04,
        1.07896881e-05, 1.03247215e-03, 3.08478352e-04, 5.09202666e-01,
        2.43081442e-07, 1.03789364e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[5.58265705e-07, 3.07239482e-03, 9.95598278e-01, 2.37007320e-03,
        6.11044172e-06, 1.91687312e-04, 7.70787235e-02, 1.97036970e-03,
        6.80150707e-04, 5.24344723e-05]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.67285510e-03, 1.61909990e-04, 7.00211672e-03, 9.93124818e-01,
        2.46600599e-04, 2.05842860e-03, 8.93506398e-06, 3.28542826e-04,
        6.76614934e-05, 2.31056591e-04]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.91559715e-05, 8.95491769e-04, 7.50352532e-03, 2.94733452e-01,
        1.11015652e-05, 2.22111488e-01, 2.29317055e-06, 3.47904549e-05,
        2.00521042e-02, 9.52087788e-05]])

predicted values - true values : 
[array([[3.59841647e-06, 4.92702649e-03, 3.01569521e-02, 9.93014923e-01,
        1.30543274e-04, 2.34887327e-03, 5.85136272e-05, 4.20550017e-05,
        8.87075105e-04, 1.06617480e-04]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.00639641e-03, 2.55488978e-05, 6.53448518e-07, 1.48639800e-05,
        8.12319360e-06, 8.23341068e-03, 6.86505013e-07, 9.99640543e-01,
        1.56069547e-06, 2.64731702e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[1.36158064e-04, 5.48215619e-05, 1.08635247e-05, 5.63614819e-05,
        9.98508370e-01, 5.11849174e-05, 8.22031820e-03, 1.69330422e-04,
        3.75087580e-06, 2.12679483e-03]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.73117731e-01, 2.29813200e-05, 1.61636572e-02, 1.45968736e-02,
        4.78389306e-07, 4.60672995e-01, 3.57224991e-06, 5.89813748e-04,
        4.71970176e-06, 2.72793572e-05]])

predicted values - true values : 
[array([[9.60421310e-03, 8.96755555e-06, 2.90073762e-05, 2.06147563e-05,
        2.28451219e-05, 3.32610066e-03, 1.71490827e-06, 9.95306314e-01,
        4.20495572e-06, 2.74286778e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[7.67656290e-02, 1.00967654e-04, 7.03445243e-04, 8.29147837e-06,
        9.39190462e-04, 1.07646732e-02, 8.83326068e-01, 3.98367210e-07,
        1.26402312e-06, 5.44329496e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[3.51075297e-01, 4.64952690e-05, 2.91710943e-03, 9.97525462e-06,
        4.82210412e-04, 9.86679494e-04, 8.84451885e-01, 8.42642477e-06,
        1.52113531e-08, 9.22389344e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[1.39304880e-03, 5.21641954e-04, 2.21927562e-03, 3.86850211e-07,
        3.21985023e-03, 7.59972845e-04, 9.90433784e-01, 2.81210674e-07,
        3.76097852e-06, 3.23861587e-03]])

predicted values - true values : 
[array([[9.81618433e-04, 1.35848685e-03, 3.73633190e-03, 9.98981235e-01,
        3.04062624e-04, 3.14642643e-04, 7.28234285e-06, 3.19633226e-04,
        5.90626609e-05, 9.74717089e-04]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[6.66294877e-04, 6.25671903e-05, 9.94466746e-01, 1.63045218e-04,
        3.90387640e-04, 4.10584702e-04, 2.62965293e-04, 6.99945957e-06,
        2.07725774e-03, 1.42764754e-02]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.63713933e-06, 2.28497768e-05, 1.58447613e-04, 6.53108585e-02,
        9.56990709e-04, 7.17275621e-06, 1.62978041e-06, 1.98207183e-01,
        2.35283060e-03, 9.94188306e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[3.10782433e-05, 5.95476184e-06, 1.12702393e-06, 2.07498546e-04,
        9.97253300e-01, 4.68521175e-03, 4.11350261e-05, 9.80871784e-05,
        8.44050397e-03, 1.65907058e-02]])

predicted values - true values : 
[array([[1.61510587e-06, 1.42111818e-05, 1.23930118e-06, 8.82344192e-05,
        4.52258003e-02, 4.43851690e-02, 1.74376810e-05, 6.68385161e-04,
        4.00493667e-02, 1.83129277e-01]])]
 - 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.37085438e-01, 5.59443134e-06, 1.17140679e-03, 5.49519100e-04,
        2.33419456e-04, 1.13295580e-03, 3.40082201e-04, 1.32451642e-02,
        1.81650111e-08, 1.56136016e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[8.89038858e-01, 1.08947090e-05, 2.85847120e-04, 3.48881803e-03,
        2.52147623e-04, 1.16007554e-03, 5.27539414e-04, 3.01180097e-03,
        1.43050636e-08, 2.59216087e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.81970095e-05, 1.39069530e-03, 7.84558345e-05, 1.87714629e-07,
        1.57039458e-04, 4.06437435e-02, 2.34426176e-04, 3.90294512e-04,
        6.15618703e-01, 1.64312061e-02]])

predicted values - true values : 
[array([[6.04547446e-05, 5.34032526e-04, 2.48619532e-08, 9.09165235e-01,
        1.10442841e-03, 1.94983776e-02, 7.53084508e-07, 3.50758318e-03,
        4.96490001e-07, 4.62016447e-03]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.76377789e-03, 4.45267226e-06, 8.95472181e-07, 6.26654244e-05,
        2.12798903e-05, 4.82661082e-03, 6.19442002e-07, 9.99510469e-01,
        3.29592488e-06, 1.62922543e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[9.75426517e-01, 4.01721940e-06, 3.19476678e-03, 1.22976426e-04,
        6.17678822e-05, 2.04354104e-03, 4.43093740e-04, 1.22368483e-02,
        5.06399862e-08, 1.87598006e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.15011839e-04, 5.37485609e-05, 6.57734987e-03, 1.83580326e-03,
        7.48396508e-06, 4.42877398e-05, 8.24121896e-06, 9.98387966e-01,
        1.26818512e-05, 6.93102455e-03]])

predicted values - true values : 
[array([[1.09389587e-01, 6.97670227e-04, 2.18458276e-06, 4.51719925e-11,
        1.09368383e-04, 9.41428479e-01, 6.44458460e-04, 1.98691816e-04,
        1.17768318e-04, 3.71770874e-04]])]
 - 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.87906784e-01, 6.89821707e-06, 6.84821402e-03, 7.47706135e-05,
        4.62728417e-06, 2.51698250e-03, 2.11132993e-02, 2.06512319e-03,
        4.84121509e-08, 2.12802780e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.51495800e-07, 7.57066320e-01, 1.33419013e-03, 3.87432976e-04,
        2.52585156e-05, 4.94806739e-04, 7.04861806e-04, 8.60903637e-03,
        5.17973595e-01, 2.49855823e-05]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.97416698e-05, 4.60710636e-05, 6.89768895e-07, 9.04256469e-04,
        7.47278944e-05, 1.05437561e-03, 3.72242690e-06, 9.80499447e-01,
        7.49441683e-04, 6.86880797e-02]])

predicted values - true values : 
[array([[1.47481709e-04, 8.07518222e-04, 6.94934306e-05, 5.04034600e-07,
        2.97801191e-04, 5.82751602e-01, 1.21610582e-05, 3.06403444e-03,
        8.73302039e-01, 7.36508417e-05]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[1.83810497e-05, 2.13298638e-02, 8.56147028e-05, 1.59112159e-07,
        2.26736005e-03, 1.86461939e-04, 8.85033552e-05, 1.18604899e-03,
        3.36874489e-01, 3.94352552e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[1.63419756e-02, 2.07104920e-05, 3.83102267e-02, 2.50263888e-02,
        2.73212954e-05, 3.69004632e-04, 1.36137557e-06, 9.73487201e-01,
        2.89836782e-05, 1.33915433e-04]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[1.50431044e-07, 8.65971936e-01, 1.19007260e-02, 9.32637359e-03,
        2.18495826e-04, 6.76869222e-05, 1.62143325e-04, 1.58486388e-02,
        1.17925119e-02, 1.99012811e-06]])

predicted values - true values : 
[array([[1.70886138e-03, 5.51780078e-04, 5.20736994e-01, 1.86929215e-02,
        1.04515576e-03, 6.27040856e-06, 1.27184022e-05, 1.04875180e-03,
        4.57454419e-06, 4.77899600e-02]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[1.49169004e-05, 1.19284804e-04, 3.96011880e-03, 7.18254633e-06,
        1.72760082e-02, 2.24110180e-04, 9.84911061e-01, 1.11053641e-06,
        7.19324014e-06, 1.42635647e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[2.83226311e-03, 2.33954401e-04, 2.45507688e-01, 7.99716465e-01,
        5.23312684e-04, 1.46300236e-04, 4.62081936e-06, 1.08687944e-03,
        3.14311330e-05, 8.56285271e-04]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.02124211e-05, 5.39983888e-03, 2.90069727e-04, 6.33697577e-06,
        9.34331635e-04, 3.63986074e-02, 1.11843081e-05, 1.09822339e-03,
        9.92933715e-01, 1.13002923e-03]])

predicted values - true values : 
[array([[3.12093386e-06, 3.47417297e-03, 5.16691245e-02, 9.57722257e-01,
        3.40826642e-03, 5.09776421e-05, 4.29236963e-06, 3.80964628e-04,
        7.80717414e-04, 1.86551936e-03]])]
 - 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.00476271e-04, 7.69792658e-06, 7.21940283e-09, 3.80728573e-04,
        9.38653863e-04, 3.69660277e-02, 4.74802400e-06, 6.31104193e-03,
        1.81341106e-05, 8.70328859e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[6.24349517e-02, 7.61771879e-05, 2.32878177e-03, 5.59752863e-06,
        1.48076251e-03, 9.16568527e-04, 9.61994157e-01, 7.24544072e-07,
        4.22098518e-08, 2.33277167e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


predicted values - true values : 
[array([[4.03097996e-07, 9.93297374e-01, 1.01000250e-02, 2.07964202e-03,
        1.29994676e-04, 1.66814565e-05, 9.66771103e-05, 3.24548080e-02,
        6.55476074e-04, 1.99076381e-06]])

predicted values - true values : 
[array([[2.18873237e-04, 1.68794399e-05, 1.44359789e-06, 2.27149664e-05,
        6.20781063e-05, 1.84463731e-03, 2.87085549e-07, 9.99125134e-01,
        9.66718595e-06, 3.81361436e-02]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


predicted values - true values : 
[array([[3.84577938e-06, 6.66665405e-03, 8.60985762e-03, 1.51736532e-03,
        2.36075204e-05, 4.41976929e-02, 4.15682311e-05, 6.53525337e-06,
        8.41746348e-01, 2.53013401e-03]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


predicted values - true values : 
[array([[3.61377466e-07, 8.38785208e-03, 1.03450167e-03, 6.69305728e-06,
        3.62098898e-03, 8.30016958e-07, 3.96475059e-03, 1.85858026e-02,
        3.89368642e-04, 8.98152736e-01]])]
 - 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


predicted values - true values : 
[array([[5.70875349e-01, 3.90735993e-05, 8.13292707e-02, 2.79741316e-07,
        7.86805395e-06, 1.62368515e-04, 1.22410969e-02, 2.50032244e-02,
        1.05302565e-07, 4.70355641e-03]])

predicted values - true values : 
[array([[9.89679890e-01, 8.73595695e-06, 6.55014360e-04, 3.12224383e-03,
        8.07353785e-06, 1.59199176e-02, 4.21036013e-04, 2.82000235e-04,
        1.11668410e-07, 4.53292420e-03]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[9.92326179e-01, 1.56859094e-05, 4.60987555e-04, 1.25101318e-02,
        9.43497543e-06, 9.03230359e-02, 1.18096436e-05, 4.24178232e-04,
        1.45396713e-07, 5.50052604e-04]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.95605128e-07, 3.24423041e-01, 2.13730819e-03, 4.76231670e-05,
        3.03551703e-03, 1.44068896e-04, 8.09380834e-04, 1.48115241e-02,
        1.63404710e-01, 1.66605164e-05]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[2.97083592e-02, 7.87334613e-06, 1.87191907e-06, 3.71092064e-05,
        3.17891241e-04, 4.15616723e-03, 4.49586823e-06, 9.97245670e-01,
        3.12613158e-07, 4.20667397e-04]])

predicted values - true values : 
[array([[2.35223274e-07, 9.90527777e-01, 1.66459069e-02, 1.01862505e-02,
        1.03596070e-03, 7.12113706e-06, 5.94909337e-05, 9.60575372e-03,
        3.82299798e-04, 2.35934970e-06]])]
 - 
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[8.81960528e-03, 1.40715587e-04, 2.05764869e-03, 1.27579492e-05,
        2.91419677e-05, 3.75397411e-04, 2.26022408e-02, 3.20832089e-05,
        4.48650841e-05, 1.99971025e-01]])]
 - 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[3.82343311e-06, 3.63620574e-02, 9.64017775e-01, 2.15001822e-02,
        1.15659432e-05, 4.17827682e-04, 1.36686666e-04, 9.68642122e-05,
        1.34888612e-01, 1.75315213e-04]])]
 - 
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


predicted values - true values : 
[array([[4.27860105e-03, 6.78467032e-03, 7.22302527e-07, 3.00718434e-01,
        1.60797585e-06, 4.50897895e-01, 1.67776854e-04, 1.81746006e-04,
        2.81437930e-07, 5.50990034e-06]])